#!name=小熊油耗
#!desc=小熊油耗解锁
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/Plugallery.png
#!homepage=https://whatshub.top
#!author=89996462
[Script]
xiaoxiongyouhao=type=http-response,pattern=^http[s]?:\/\/www.xiaoxiongyouhao.com\/api\/vip\/index.php,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/xiaoxiongyouhao.js



[MITM]
hostname = %APPEND% www.xiaoxiongyouhao.com
